name: HexViewer

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required libs
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build build-essential libx11-dev libxext-dev libxrender-dev libxrandr-dev libxcursor-dev libxft-dev curl -y

      - name: Build HexViewer
        run: |
          chmod a+x build_linux.sh
          ./build_linux.sh
          mv build/HexViewer build/hexviewer_linux

      - name: Upload Linux Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: build/src/console/cdie_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build HexViewer
        run: |
          pwd
          build_win.bat

      - name: Upload Windows Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: build/HexViewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required libs
        run: |
          brew update
          brew install cmake

      - name: Build HexViewer
        run: |
          chmod a+x build_macos.sh
          ./build_macos.sh
          mv build/HexViewer build/hexviewer_macos

      - name: Upload macOS Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: build/hexviewer_macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
